# Example theme from https://github.com/greshake/i3status-rust/issues/868#issue-722772399
idle_bg = "#44475a"
idle_fg = "#f8f8f2"
info_bg = "#44475a"
info_fg = "#f8f8f2"
good_bg = "#50fa7b"
good_fg = "#f8f8f2"
warning_bg = "#f1fa8c"
warning_fg = "#f8f8f2"
critical_bg = "#ff5555"
critical_fg = "#f8f8f2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "f8f8f2"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
