backlight = [
    "ğŸŒ•",
    "ğŸŒ”",
    "ğŸŒ“",
    "ğŸŒ’",
    "ğŸŒ‘",
]
bat_charging = "ğŸ”Œ"
bat = [
    "ğŸª«",
    "ğŸ”‹",
]
bat_not_available = "ğŸª«"
bell = "ğŸ””"
bell-slash = "ğŸ”•"
bluetooth = "ğŸ”µğŸ¦·"
calendar = "ğŸ“…"
cogs = "âš™ï¸"
cpu = "ğŸ¤–"
cpu_boost_off = "ğŸ¢"
cpu_boost_on = "ğŸ‡"
disk_drive = "ğŸ’½"
docker = "ğŸš¢"
github = "ğŸ™ğŸ±"
gpu = "ğŸ–¥ï¸"
headphones = "ğŸ§"
joystick = "ğŸ®"
keyboard = "âŒ¨ï¸"
mail = "ğŸ“¨"
memory_mem = "ğŸ’­"
memory_swap = "ğŸ’½"
mouse = "ğŸ–±ï¸"
music = "ğŸµ"
music_next = "â­ï¸"
music_pause = "â¸ï¸"
music_play = "â–¶ï¸"
music_prev = "â®ï¸"
net_bridge = "ğŸŒ‰"
net_cellular = "ğŸ“¶"
net_down = "â¬‡ï¸"
net_loopback = "â°ğŸ”™"
net_modem = "â˜ï¸"
net_up = "â¬†ï¸"
net_vpn = "ğŸ”’"
net_wired = "ğŸŒ"
net_wireless = "ğŸ›œ"
notification = "ğŸ””"
phone = "ğŸ“±"
phone_disconnected = "ğŸ“µ"
ping = "ğŸ“"
pomodoro = "ğŸ…"
pomodoro_break = "â˜•"
pomodoro_paused = "â¸ï¸"
pomodoro_started = "â–¶ï¸"
pomodoro_stopped = "â¹ï¸"
resolution = "ğŸ”³"
tasks = "âœ…"
tea = "â˜•"
thermometer = "ğŸŒ¡ï¸"
time = "ğŸ•‘"
toggle_off = "ğŸ”´"
toggle_on = "ğŸŸ¢"
unknown = "â“"
update = "â¬†ï¸"
uptime = "ğŸ•‘"
volume = [
    "ğŸ”ˆ",
    "ğŸ”‰",
    "ğŸ”Š",
]
volume_muted = "ğŸ”‡"
microphone = "ğŸ¤ğŸŸ¢"
microphone_muted = "ğŸ¤ğŸ”´"
weather_clouds = "â˜ï¸"
weather_clouds_night = "â˜ï¸"
weather_default = "â˜ï¸"
weather_fog = "ğŸŒ"
weather_fog_night = "ğŸŒ"
weather_moon = "ğŸŒœ"
weather_rain = "ğŸŒ§ï¸"
weather_rain_night = "ğŸŒ§ï¸"
weather_snow = "ğŸŒ¨ï¸"
weather_sun = "ğŸŒ"
weather_thunder = "ğŸŒ©ï¸"
weather_thunder_night = "ğŸŒ©ï¸"
webcam = "ğŸ¥"
xrandr = "ğŸ–¥ï¸"
