# Material Design icons by Google
# https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints
backlight = [
    "\ue1ad", # brightness_low
    "\ue3a6", # brightness_1
    "\ue3a7", # brightness_2
    "\ue3a8", # brightness_3
    "\ue3a9", # brightness_4
    "\ue3aa", # brightness_5
    "\ue3ab", # brightness_6
    "\ue3c8", # brightness_7
    "\ue1ac", # brightness_high
]
bat_charging = "\ue3ac" # battery_charging_full
bat_not_available = "\ue1a6" # battery_unknown
bat = [
    "\ue19c", # battery_alert
    "\ue1a5", # battery_std
    "\ue1a5", # battery_std
    "\ue1a5", # battery_std
    "\ue1a5", # battery_std
    "\ue1a5", # battery_std
    "\ue1a5", # battery_std
    "\ue1a5", # battery_std
    "\ue1a5", # battery_std
    "\ue1a4", # battery_full
]
bell = "\ue7f4" # notifications
bell-slash = "\ue7f8" # notifications_paused
bluetooth = "\ue1a7" # bluetooth
calendar = "\ue935" # calendar_today | TODO: broken?
cogs = "\ue8b8" # settings
cpu = "\ue640" # network_check
cpu_boost_on = "\ue837" # radio_button_on
cpu_boost_off = "\ue836" # radio_button_off
disk_drive = "\ue1db" # storage
docker = "\ue532" # directions_boat
github = "\ue86f" # code
gpu = "\ue333" # tv
headphones = "\ue60f" # bluetooth_audio
joystick = "\ue30f" # gamepad
keyboard = "\ue312" # keyboard
mail = "\ue0be" # email
memory_mem = "\ue322" # memory
memory_swap = "\ue8d4" # swap_horiz
mouse = "\ue323" # mouse
music = "\ue405" # music_note
music_next = "\ue044" # skip_next
music_pause = "\ue034" # skip_next
music_play = "\ue037" # play_arrow
music_prev = "\ue045" # skip_previous
net_bridge = "\uefe6" # cable | TODO: broken?
net_down = "\uf090" # download
net_loopback = "\ue028" # loop
net_modem = "\uefe6" # cable | TODO: broken?
net_cellular = [
        "\ue1d0", # signal_cellular_off
        "\uf0a8", # signal_cellular_0_bar
        "\uf0a9", # signal_cellular_1_bar
        "\uf0aa", # signal_cellular_2_bar
        "\uf0ab", # signal_cellular_3_bar
        "\ue1c8", # signal_cellular_4_bar
]
net_up = "\uf09b" # upload
net_vpn = "\ue0da" # vpn_key
net_wired = "\uefe6" # cable | TODO: broken?
net_wireless = "\ue63e" # wifi | TODO: progression based on signal strength
notification = "\ue7f7" # notifications_active
phone = "\ue324" # phone_android
phone_disconnected = "\ue339" # device_unknown
ping = "\ue62a" # system_update
pomodoro = "\U0001f345" # https://unicode-table.com/en/1F4F5/
pomodoro_break = "\uefef" # coffee | TODO: broken?
pomodoro_paused = "\ue034" # pause
pomodoro_started = "\ue037" # play_arrow
pomodoro_stopped = "\uef6a" # play_disabled ef6a | TODO: broken?
resolution = "\uf152" # crop-square-rounded
tasks = "\ue8f9" # work
tea = "\uefef" # coffee
thermometer = "\ue1ff" # device_thermostat | TODO: broken?
time = "\ue192" # access_time
toggle_off = "\ue836" # radio_button_on
toggle_on = "\ue837" # radio_button_on
unknown = "\ueb8b" # question_mark | TODO: broken?
update = "\ue8d7" # system_update_alt
uptime = "\ue425" # timer
volume = [
    "\ue04e", # volume_mute
    "\ue04d", # volume_down
    "\ue050", # volume_up
]
volume_muted = "\ue04f" # volume_off
microphone = [
    "\ue02a", # mic_none
    "\ue029", # mic
    "\ue029", # mic
]
microphone_muted = "\ue02b" # mic_off
weather_clouds = "\ue42d" # wb_cloudy
weather_clouds_night = "\uea46" # nights_stay
weather_default = "\ue42d" # wb_cloudy
weather_fog = "\ue42d" # wb_cloudy
weather_fog_night = "\ue42d" # wb_cloudy
weather_moon = "\uf03d" # nightlight
weather_rain = "\ue798" # water_drop
weather_rain_night = "\ue798" # water_drop
weather_snow = "\ueb3b" # ac_unit
weather_sun = "\ue430" # wb_sunny
weather_thunder = "\uebdb" # thunderstorm
weather_thunder_night = "\uebdb" # thunderstorm
webcam = "\ue04b" # videocam
xrandr = "\ue31e" # laptop
